name: PHP Code Sniffer

on:
  push:
    branches:
      - dev
      - fix
      - master
  pull_request:
    branches:
      - dev
      - master

jobs:
  psalm:
    name: PHP Code Sniffer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Run PHP Code Sniffer
        run: ./vendor/bin/phpcs --config-set installed_paths vendor/phpcompatibility/php-compatibility && .vendor/bin/phpcs --standard=tests/.phpcs.xml